### ISSUE TITLE
Refactor validator module to hold a Validator Class

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/pyoblib#118]
This will allow validator to be initialized by passing a taxonomy instance into its __init__ method (very similar to other modules) and eliminate the need for the taxonomy singleton currently in taxonomy.py.  Part of this change should also include removing the singleton from taxonomy.py.

**Comment by cwhanse** [comment]
Within the scope of this change, all functions are moved to `Validator` methods.  Is that what we intend?

**Comment by michael-bbs** [comment]
code fix merged
