### ISSUE TITLE
Merge Taxonomy Python Files

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/pyoblib#145]
Current thinking is to have Taxonomy.py for accessing the Metadata and taxonomy_loader.py to load the Taxonomy.

Please note that concurrence on this needs to occur or this will be bumped out to 1.1.0.

**Comment by cwhanse** [comment]
@joelebwf are you waiting on us for this issue?

**Comment by cwhanse** [comment]
oh nvm see your note on slack
