### ISSUE TITLE
cli overloads builtin parser

### ISSUE THREAD

**Issue by cwhanse** [SunSpecOrangeButton/pyoblib#147]
[this](https://github.com/SunSpecOrangeButton/pyoblib/blob/master/scripts/cli/cli.py#L327) should change, suggest `argparser = `...

**Comment by joelebwf** [comment]
How about parent_parser?  "parser" is verbatim out of the argparser documentation but they also use parent_parase in some examples.

**Comment by cwhanse** [comment]
I don’t have a strong preference for name as long as it is not parser. The risk is a 3rd party using oblib’s cli in a python environment where they are also using python parser for io functions.

Sent from my iPhone

On Feb 25, 2019, at 11:23 AM, joelebwf <notifications@github.com<mailto:notifications@github.com>> wrote:


How about parent_parser? "parser" is verbatim out of the argparser documentation but they also use parent_parase in some examples.
