### ISSUE TITLE
Updates for OBTV support

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/pyoblib#183]
Various updates need to be made for OBTV support.  Generally speaking this involves adding getters to the Taxonomy class and in some cases loading additional data from the solar-taxonomy.  There is also some data (complex units, glossary, and such) that could be added but will need to be discussed with the Taxonomy Standards commit (this is noted by the bullet point).  This is a running list:

- A getter needs to be available that supplies Entrypoints and indicates if they are Data, Documents, or Process.
- XBRL base types need to be returned.
- Additional information on what type of programming data type and validation rules for XBRL and OB types should be better exposed.
- Entrypoint documentation needs to be returned.
- Complex units need to be returned (subject to standards committee inclusion).
- Glossary items (abbreviations, acronyms, etc...) could be returned (subject to standards committee inclusion).

**Comment by cwhanse** [comment]
Here's the [section](http://www.xbrl.org/Specification/XBRL-2.1/REC-2003-12-31/XBRL-2.1-REC-2003-12-31+corrected-errata-2013-02-20.html#_4.8.4) of the spec that describes how complex units are written in an XBRL instance

**Comment by joelebwf** [comment]
The UTR.xml is not following the specification.  Instead of containing numerator and denominator it contains numeratorItemType and denominatorItemType

      <unitId>Energy_per_Duration</unitId>
      <unitName>Energy/Duration</unitName>
      <itemType>flowItemType</itemType>
      <numeratorItemType>energyItemType</numeratorItemType>
      <nsNumeratorItemType>http://www.xbrl.org/2009/utr</nsNumeratorItemType>
      <denominatorItemType>durationItemType</denominatorItemType>

Also the spec says that the numerator and denominator cannot be the same value but they clearly our (or at least the itemTypes) for monetary_per_monetary:

      <unitId>Monetary_per_Monetary</unitId>
      <unitName>Monetary/Monetary</unitName>
      <itemType>pureItemType</itemType>
      <nsItemType>http://www.xbrl.org/2003/instance</nsItemType>
      <itemTypeDate>2003-12-31</itemTypeDate>
      <numeratorItemType>monetaryItemType</numeratorItemType>
      <nsNumeratorItemType>http://www.xbrl.org/2003/instance</nsNumeratorItemType>
      <denominatorItemType>monetaryItemType</denominatorItemType>

**Comment by cwhanse** [comment]
The way I read the spec, unitNumerator and unitDenominator aren't set until an instance is created so those elements aren't part of the UTR. I could easily be wrong.
