### ISSUE TITLE
Docstrings require additional information.

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/pyoblib#75]
Docstrings throughout all of the code need to have data types for all input and return values.  Also classes need information on member attributes and exceptions that can be raised need to be documented.  This is for all classes, methods, and functions in all code files.

**Comment by joelebwf** [comment]
This should be by module:

Jono - data_model
Joel - taxonomy modules
Michael - Validator
Cliff - All other modules
Jessie - Validate that readthedocs is correctly reflecting everything

**Comment by joelebwf** [comment]
Completed my section and removed myself from assignee's.

**Comment by cwhanse** [comment]
Recommend we close this issue. It looks to me that all code modules have docstrings.  #139 #114 others.

readthedocs build is part of deployment and should be tracked separately.
