### ISSUE TITLE
Entrypoint class should accept all concepts by default unless a restriction is added

### ISSUE THREAD

**Issue by jonoxia** [SunSpecOrangeButton/pyoblib#80]
The workflow should be:

i create an Entrypoint instance (the class might be renamed to make this clearer) -- it can hold any kind of concept. (corresponding to the "All" entrypoint).

then, optionally, i call something like doc.restrictToEntrypoint("CutSheet") -- from this point on, attempting to set any concepts not in CutSheet will fail. It's an optional restriction that I can put on myself, rather than a requirement.

Setting a list of allowed cutsheets (e.g. ["System", "Site"]) should also be supported.

**Comment by shelcrow** [comment]
Entrypoint has been renamed to OBInstance
