### ISSUE TITLE
In TaxonomyUnits is_unit() and is_unit2() should be conflated

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/pyoblib#89]
is_unit() and is_unit2() were created as part of the refactor and are essentially overloaded methods.  They should be conflated.  A discussion is probably needed as to how best to do so and the methodology adopted here is probably useful in a go forward manner since its likely the same pattern will occur in the future.

**Comment by cwhanse** [comment]
I propose we combine `is_unit` and `is_unit2` with the behavior that True is return is the input corresponds to a valid unit.  Input is a string which can be an `id`, `unit_id`, or `unit_name`.   We probably need additional `get_` methods that return a specific unit.
